### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by CptnRoughnight** [Starpelly/raylib-beef#6]
Hi,
I've managed to compile the example under Linux with shared libraries.

TODO:

In File:
raylib-beef/BeefProj.toml :

Add:

[Configs.Debug.Linux64]
OtherLinkFlags = "$(LinkFlags) -lraylib -lGL -lm -lpthread -ldl -lrt -lX11"

**Comment by Starpelly** [comment]
feel free to open a pr

**Comment by Starpelly** [comment]
Eh, I'll do this eventually
